= Sample gradle CI / CD
:icons: font

This is a sample gradle project that tests various continuous integration and delivery services.
It is a very simple spring boot based web application.
The repository can be found at https://github.com/westernacher-solutions/sample-ci-cd .

== Travis CI

The https://travis-ci.org continuous integration service automatically builds the github repository after each push to the configured branch.
The current repository can be found at https://travis-ci.org/westernacher-solutions/sample-ci-cd image:https://api.travis-ci.org/westernacher-solutions/sample-ci-cd.svg?branch=master[status].
A link:.travis.yml[.travis.yml] configuration file with some basic setup is needed for building.
Travis runs the tests but does not visualize the junit report files.
It is recommended to enable the test reporting in link:build.gradle[build.gradle].

== Snap CI

- https://snap-ci.com
- requires organization authorization

== Codefresh

- https://codefresh.io
- Does not support github organisations directly but can be configured with any github URL.
- Codefresh web ui shows 'not found'. :(

== zeit now

The https://zeit.co build and deployment service is a build and deployment service.
It does not provide a full web UI but a command line tool instead.

NOTE: It must be installed initially with `npm install -g now`.

The build and deployment process is started by running `now`.
The very first run of `now` asks for your email address for authentication.
It works like a charm!
The now tool copies the target URL into the clipboard.
Opening this url in the browser either shows the running build process or the deployed web app after deployment has finished.

== use your own docker

- build image: `docker build . -t sample-ci-cd`
- start a fresh container: `docker run -it --rm -p8080:8080 sample-ci-cd`
- navigate to http://localhost:8080

== run it locally without docker

- build and test it: `./gradlew build`
- start the webapp: `./gradlew bootRun`
- navigate to http://localhost:8080
